
name: 'Terminating Resources'

on:
  push:
    branches: [ "*"]
    
permissions:
  id-token: write
  contents: read


jobs:
  terraform_plan:
    name: 'Review'
    runs-on: ubuntu-latest
    environment: Review

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::806066816337:role/OIDC-Github-Workflow-Config
        role-session-name: Dev-EnvironmentRole-S3Prod
        aws-region: eu-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

  terraform_destroy:
    name: 'Shutting-Down Resources'
    runs-on: ubuntu-latest
    environment: Live Production
    needs: terraform_plan
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::806066816337:role/OIDC-Github-Workflow-Config
        role-session-name: Dev-EnvironmentRole-S3Prod
        aws-region: eu-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false



              